#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_address_index:
  path: /
  controller: App\Controller\AddressController::index

app_address_store:
  path: /store
  controller: App\Controller\AddressController::store